language: objective-c
osx_image: xcode61
rvm use ruby-2.0.0-p0@routerscript
rvm --create ruby-2.0.0-p0@routerscript
rvm rvmrc to .ruby-version
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
